AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*.rb'
