# Use the follow settings allowing you to just copy this to config/database.yml

default: &default
  adapter: postgresql
  username: <%= ENV['POSTGRES_USERNAME'] %>
  host: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: development_ai_colaboration_platform

test:
  <<: *default
  database: test_ai_colaboration_platform

production:
  <<: *default
  database: production_ai_colaboration_platform
