development:
  server: ENV['SERVER']
  secret_token: ENV['SECRET_TOKEN']
test:
  server: ENV['SERVER']
  secret_token: ENV['SECRET_TOKEN']
production:
  server:  ENV['SERVER_PRODUCTION']
  secret_token: ENV['SECRET_TOKEN_PRODUCTION']
  signature_expiration: ENV['EXPIRATION']
